[package]
name = "cli-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
serde_derive = "1.0.210"
api_handler = { path = "../api_handler" }
serde_json = "1.0.128"
clap = { version = "4.5.19", features = ["derive"] }
log = "0.4.22"
eval = "0.4.3"